server:
  port: 8080

spring:
  application:
    name: customer

datasource:
  url: jdbc:postgres://localhost:5432/customer
  username: postgres
  password: secret
  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
      format_sql: 'true'
    show_sql: 'true'
    hibernate:
      ddl-auto: update
