server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: admin
    password: secret
    url: jdbc:postgresql://localhost:5432/customer-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl_auto: update
    show_sql: 'true'
    format_sql: 'true'
